version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - FLASK_DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  worker:
    build:
      context: .
    command: celery -A tasks worker --loglevel=info --logfile=/app/logs/celery.log --events
    depends_on:
      - redis
      - app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  flower:
    build:
      context: .
    command: celery -A tasks flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
